### ISSUE TITLE
secret.py

### ISSUE THREAD

**Issue by specs32** [kaulketh/ledpibot#35]
hello, great project, i would like to try it out, but i have trouble creating the required files for the bot to run ...
could you provide a sample configuration for the secrets and all required files please !

**Comment by kaulketh** [comment]
hello, here an example for  "secret.py"
`
#!/usr/bin/python3
# -*- coding: utf-8 -*-
# github (if required)
access_token_to_github = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# chat id's of allowed users/admin of the created telegram bot
annib = 123456789
thk = 123456789
# token of bot (get from telegram botFather)
token = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
`

**Comment by kaulketh** [comment]
dont forget to update **access.py** if any changes at variables in **secret.py**

```
#!/usr/bin/python3
# -*- coding: utf-8 -*-

__author___ = "Thomas Kaulke"
__email__ = "kaulketh@gmail.com"
__maintainer___ = "Thomas Kaulke"
__status__ = "Production"

from . import secret

# github
access_token_to_github = secret.access_token_to_github

# bot
**annib** = secret.**annib**
**thk** = secret.**thk**
token = secret.token

if __name__ == '__main__':
    pass
```

furthermore maybe its needed to update the **admins** list/array in the bot classes
**telepotBot.py**
line 32
```admins = [access.thk, access.annib]```
**telegramBot.py**
line 30
```admins = [access.thk, access.annib]```

**Comment by kaulketh** [comment]
More information can be found in [manual](https://github.com/kaulketh/ledpibot/blob/master/MANUAL.md). Also refer [hardware description](https://github.com/kaulketh/ledpibot/blob/master/hardware/HARDWARE.md).

**Comment by kaulketh** [comment]
Additionally if you want to update the program stuff and it is stored on github its required to adapt **update.py**
line 14 - 17
```
GIT = "https://github.com/kaulketh/ledpibot.git"
HOME_PI_BOT = "/home/pi/bot"
PROJECT = "ledpibot"
SECRET = "secret.py"
```

**Comment by specs32** [comment]
Thank you ! 
got it working right away...
